### ISSUE TITLE
Can I fork this repo to publish my own content?

### ISSUE THREAD

**Issue by pbamotra** [samsymons/samsymons.com#3]
Hi Sam,

I like the minimal design on you blog. I wanted to know if I can fork this theme and do modifications to publish my blog content on machine learning?

Thanks
Pankesh

**Comment by samsymons** [comment]
Hey @pbamotra, sorry for the slow reply!

I am totally fine if you would like to take this blog design and use it yourself. Unfortunately, I can't offer much help with hosting, since I host this myself on a custom Digital Ocean VPS. But, I think it would be quite easy to host on something like GitHub Pages.

But of course, feel free to use this design yourself. (And let me know when your blog is live, I would love to read it!)
